### ISSUE TITLE
GLX API_UNAVAILABLE

### ISSUE THREAD

**Issue by nico202** [JuliaGL/GLFW.jl#106]
Hi, I'm on:+
```
    julia 0.5
    system: NixOS (linux)

```
I import the module, but when I call:
 `   window = GLFW.CreateWindow(640, 480, "GLFW.jl")`
I get the following error:
`    ERROR: GLFWError (API_UNAVAILABLE): GLX: Failed to load GLX`

Am I missing a Library? Don't know how to figure out how to fix it
Thanks, Nicolò

**Comment by SimonDanisch** [comment]
Do you have video drivers and x server installed?!

**Comment by nico202** [comment]
Answering myself: I was missing mesa

**Comment by nico202** [comment]
@SimonDanisch Yes X server is running, but mesa was not in the LD_LIBRARY_PATH
