### ISSUE TITLE
timer related functions not present

### ISSUE THREAD

**Issue by PinkMushroom** [JuliaGL/GLFW.jl#166]
Hi,

I'm talking about things like SetTime, GetTime, etc...

I'm very interested in making a PR and adding them, since I believe they would be very straightforward.

Is there any particular branch I should use for the PR, or just fork master ?

**Comment by jayschwa** [comment]
Hi @PinkMushroom, thanks for your interest. As mentioned in the README, `GetTime` and friends are not provided since they are redundant with functionality that is already present in the Julia standard library. https://docs.julialang.org/en/stable/stdlib/Dates/

**Comment by PinkMushroom** [comment]
doh!

it looks like the time() function will be the most direct equivalent, which is not in Dates.

thanks.  I'm making a lot of use of GLFW.  Maybe I'll find a way to contribute :-)
