### ISSUE TITLE
Version Mismatch

### ISSUE THREAD

**Issue by wsrinin** [JuliaGL/GLFW.jl#176]
Hi,

It am not sure whether the following snippet give me the correct version of my openGL

`window = GLFW.CreateWindow(10, 10, "OpenGL Example")
    # Make the window's context current
    GLFW.HideWindow(window)
    GLFW.MakeContextCurrent(window)
    glversion = unsafe_string(glGetString(GL_VERSION))`

I am pretty confident that the version of the openGL on my mac book is 4.1 but somehow the above snippet give me 2.4. What could be the possible source of this disagreement?

Best,

**Comment by jayschwa** [comment]
You probably need to pass context hints before creating the window. Some platforms return older versions of OpenGL to remain backwards compatible with older applications.

https://www.glfw.org/docs/latest/window_guide.html#window_hints_ctx

**Comment by wsrinin** [comment]
Thank you for the clarification. Indeed, that is precisely what I need to do.
