### ISSUE TITLE
GLFW does not rebuild correctly after build failure

### ISSUE THREAD

**Issue by natschil** [JuliaGL/GLFW.jl#178]
I try to install/update GLFW without setting ENV["DISPLAY"] or having the necessary dependencies installed  every now and then, which causes a build failure. When I try to manually rebuild it using `build GLFW` in the REPL, I get no errors (even though I should be getting errors). 

The only way I know to get around this is to run `rm GLFW` and then `gc`, and to then `add GLFW`.

**Comment by jayschwa** [comment]
I can confirm this is a problem on Ubuntu. However, it may not be possible to fix in GLFW.jl since it's using BinDeps.jl to do all the heavy lifting.

**Comment by musm** [comment]
close ? Since this got upgraded to BinaryBuilder
