### ISSUE TITLE
Missing MonitorProperties

### ISSUE THREAD

**Issue by Gilga** [JuliaGL/GLFW.jl#193]
Yeah, this cannot work..... where did MonitorProperties go?

https://github.com/JuliaGL/GLFW.jl/blob/0950b84ee9ce81e9d62c6882461a33e352529803/src/glfw3.jl#L671

**Comment by jayschwa** [comment]
Thanks for the report. It looks like that function was broken for a long time. I will register the fix with the Julia package manager soon.
