### ISSUE TITLE
Upgrade to 3.3.2

### ISSUE THREAD

**Issue by SimonDanisch** [JuliaGL/GLFW.jl#195]
I actually kinda lost track, what would need to happen to upgrade :D 
But an upgrade could help with e.g.: https://github.com/JuliaPlots/Makie.jl/issues/393#issuecomment-579699902

**Comment by asinghvi17** [comment]
I think we just need to change the binary in GLFW_jll, and bump compat here?

**Comment by SimonDanisch** [comment]
Allright, lets see: https://github.com/JuliaPackaging/Yggdrasil/pull/447
