### ISSUE TITLE
EGL support?

### ISSUE THREAD

**Issue by VarLad** [JuliaGL/GLFW.jl#208]
Does GLFW.jl provide for WAYLAND?
GLFW has now support for EGL so....
Currently, although it builds...
Running with Makie...
ERROR: GLFWError (VERSION_UNAVAILABLE): GLX: Failed to create context: GLXBadFBConfigERROR: GLFWError (VERSION_UNAVAILABLE): GLX: Failed to create context: GLXBadFBConfig
For Wayland systems, glx doesn't work with nvidia drivers... egl does...
Can someone look into this?

**Comment by jayschwa** [comment]
Issue #188 is for adding Wayland support.
