### ISSUE TITLE
unable to load GLMakie

### ISSUE THREAD

**Issue by IgorDouven** [JuliaGL/GLFW.jl#231]
Hi,

I updated my packages and am now unable to load GLMakie. I'm getting the following message:
```
┌ Warning:     GLFW couldn't create an OpenGL window.
│     This likely means, you don't have an OpenGL capable Graphic Card,
│     or you don't have an OpenGL 3.3 capable video driver installed.
│     Have a look at the troubleshooting section in the GLMakie readme:
│     https://github.com/MakieOrg/Makie.jl/tree/master/GLMakie#troubleshooting-opengl.
└ @ GLMakie ~/.julia/packages/GLMakie/9nid7/src/screen.jl:228
ERROR: LoadError: GLFWError (VERSION_UNAVAILABLE): GLX: Failed to create context: BadValue
```
I also updated Arch, so I'm not sure what is causing the problem. Any help would be much appreciated.

**Comment by matthieu-perso** [comment]
Hi @IgorDouven - this looks like your GPU isn't compatible with your OpenGL version. 

Check your OpenGL version. Once you have this, you can check your GPU. 

**For mac :**
`system_profiler SPDisplaysDataType
`
**For windows:**
`wmic path win32_videocontroller get caption, name, deviceid, adapterram
`

Based on this, you should be able to downgrade OpenGL to the relevant version supported by our computer.
