### ISSUE TITLE
Document rationale for omitted bindings

### ISSUE THREAD

**Issue by jayschwa** [JuliaGL/GLFW.jl#25]
Example: GLFW's clipboard functions are left out because they're redundant with Julia's [`Base.clipboard`](http://docs.julialang.org/en/latest/stdlib/base/#Base.clipboard).

**Comment by Gnimuc** [comment]
Was glfwGetTime() and glfwSetTime() omitted for the same reason?   I know Julia has a Base.time function, but this function seems to get the system time as output, not the time elapsed since GLFW was initialized.

**Comment by jayschwa** [comment]
Yes. Use Julia's [`Base.time_ns`](http://docs.julialang.org/en/release-0.3/stdlib/base/?highlight=time_ns#Base.time_ns) for a high-precision monotonic clock. If you specifically need to know elapsed time, then save an offset when you start and subtract it from subsequent calls.

**Comment by jayschwa** [comment]
The README mentions this.
