### ISSUE TITLE
Need cmake on OS X

### ISSUE THREAD

**Issue by dlfivefifty** [JuliaGL/GLFW.jl#26]
build failed on OS X (Mavericks), until after I ran

brew install cmake

**Comment by Gnimuc** [comment]
have you fixed that?     maybe run `brew update` first?

**Comment by SimonDanisch** [comment]
I think this issue is fixed, but the question is about how we can automate this. The problem is, that not everyone has brew installed and @jayschwa  and me aren't very familiar with automating these kind of tasks...

**Comment by dlfivefifty** [comment]
Yes my fix was to add “brew cmake” to my julia install instructions

**Comment by jayschwa** [comment]
Closing this issue as obsolete. The newest version of GLFW.jl now downloads pre-compiled Homebrew binaries and no longer attempts to build from source.
