### ISSUE TITLE
Should this work with OpenGL.jl?

### ISSUE THREAD

**Issue by nathanielvirgo** [JuliaGL/GLFW.jl#29]
I'm old-fashioned (read: short of time for learning new tricks), and would like to use deprecated OpenGL functions like glMatrixMode.

Since these functions aren't included in ModernGL.jl, I thought I'd try using GLFW with OpenGL 1.0 from OpenGL.jl. However, the following code displays a black window and turns my Macbook Pro into treacle until I manage to force-quit it. Am I doing something wrong, or is this impossible?

```
using OpenGL
@OpenGL.version "1.0"
@OpenGL.load
import GLFW

GLFW.Init()

window = GLFW.CreateWindow(640, 480, "GLFW.jl")

GLFW.MakeContextCurrent(window)

w = 640
h = 480

glViewport(0,0,w,h)
glMatrixMode(GL_PROJECTION)
glLoadIdentity()
gluPerspective(45.0,w/h,0.1,100.0)
glMatrixMode(GL_MODELVIEW)

while !GLFW.WindowShouldClose(window)

    glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT)
    
    glLoadIdentity()

    glColor(1.0,1.0,1.0)

    glTranslate(-1.5,0.0,-6.0)

    glBegin(GL_POLYGON)
      glVertex(0.0,rand(),0.0)
      glVertex(1.0,-1.0,0.0)
      glVertex(-1.0,-1.0,0.0)
    glEnd()

    glTranslate(3.0,0.0,0.0)

    glBegin(GL_QUADS)
        glVertex(-1.0,1.0,0.0)
        glVertex(1.0,1.0,0.0)
        glVertex(1.0,-1.0,0.0)
        glVertex(-1.0,-1.0,0.0)
    glEnd()
    end

	GLFW.SwapBuffers(window)

	GLFW.PollEvents()
end

GLFW.Terminate()
```

**Comment by SimonDanisch** [comment]
Is this still relevant?

**Comment by nathanielvirgo** [comment]
As far as I know yes. At least, I still don't have a way to use the OpenGL fixed pipeline on OS X without using GLUT.

**Comment by jayschwa** [comment]
I don't think there's anything actionable for GLFW.jl here. The package is only a wrapper for the the library's C API. If you suspect there's an issue with the library, it lives at https://github.com/glfw/glfw.

**Comment by nathanielvirgo** [comment]
Hmm. Well maybe it works in C and maybe it doesn't, but the question was whether this package is supposed to work with OpenGL.jl, which is a Julia package, not a C one. Do I take it the answer to this question is "no, this is not supported"?

**Comment by nathanielvirgo** [comment]
Hi, just for clarification - this means the answer to my question is "no, this is not supported", right? (The question is about the interoperation of two Julia packages, GLFW.jl and OpenGL.jl - it might be that they're incompatible due to issues at the C level, but as a mostly non-C programmer I can't really address that. All I really wanted to know was whether I should expect them to work together at the Julia level.)

**Comment by jayschwa** [comment]
I haven't tried the two together before, but I can't think of anything that would make them incompatible at the Julia level. More specifically, I would expect a working GLFW + legacy OpenGL demo written in C to continue working if translated to Julia.

**Comment by SimonDanisch** [comment]
They should in theory work together, but OpenGL.jl is in a dire state, so it might just work on linux( if at all). On windows and Mac OS it shouldn't work, if I remember correctly ( At least for versions higher than 3.0).
I've never got around to integrate the fixes from ModernGL into OpenGL. There where quite drastic changes;)
So I have two options for you. Use ModernGL together with GLAbstraction ( shouldn't be very difficult) or, if you insist on OpenGL 1.0, I can give you directions for making a working legacy package out of OpenGL.jl.
By the way, you might create the context incorrectly for GLFW, if OpenGL.jl actually works with GLUT.jl.
You should try something like this for Mac OS ( I can't test this, as I'm on windows)
```Julia
	GLFW.Init()
	@osx_only begin
		GLFW.WindowHint(GLFW.CONTEXT_VERSION_MAJOR,2)
		GLFW.WindowHint(GLFW.CONTEXT_VERSION_MINOR, 1)
		GLFW.WindowHint(GLFW.OPENGL_FORWARD_COMPAT, GL_FALSE)
		GLFW.WindowHint(GLFW.OPENGL_PROFILE, GLFW.OPENGL_COMPAT_PROFILE)
	end
	window = GLFW.CreateWindow(w, h, name)
	GLFW.MakeContextCurrent(window)
	GLFW.ShowWindow(window)
```
http://www.glfw.org/docs/latest/window.html#window_hints
