### ISSUE TITLE
Build fails on Windows / Julia v0.4

### ISSUE THREAD

**Issue by dextorious** [JuliaGL/GLFW.jl#34]
Feel free to close this if GLFW isn't meant to be compatible with the current master branch of Julia (I looked, but didn't see it specified anywhere).

Currently, Pkg.build("GLFW") on Windows fails with the following error:

"LoadError: could not spawn `cp -R builds/glfw-3.0.4.bin.WIN32/lib-mingw usr32/lib`: no such file or directory (ENOENT)
while loading C:\Users\admin\.julia\v0.4\GLFW\deps\build.jl, in expression starting on line 38"

Is there an additional dependency I should install?

**Comment by SimonDanisch** [comment]
I'm not entirely sure why this happens, but on windows you should be able
to fix this by simply installing glfw yourself.

GLFW.org seems to be down, though...

On the other side, cp on windows is very brittle and doesn't produce good
error messages.

If you want to debug this a little further, you can try to just execute the
command from the  error message yourself and see what's going on.

**Comment by jayschwa** [comment]
Thanks for the report. It's probably the case that I need to switch to using the Julia `cp` function rather than calling out to an external `cp`.

**Comment by jayschwa** [comment]
Please re-test from master and let me know if my commit worked or not.
``` julia
Pkg.update()
Pkg.checkout("GLFW")
Pkg.build("GLFW")
```

**Comment by dextorious** [comment]
It works fine now! Thanks for the quick response and fix.

**Comment by SimonDanisch** [comment]
I tested your changes on windows and linux and both are working as well!
