### ISSUE TITLE
Automatic donwload fai

### ISSUE THREAD

**Issue by UrbanKristan** [JuliaGL/GLFW.jl#44]
I got this error when running Pkg.build("GLFW")

automatic download failed (error: 2148270085): https://github.com/glfw/glfw/releases/download/3.1.1/glfw-3.1.1.bin.WIN32.zip
while loading C:\Users\user\.julia\v0.3\GLFW\deps\build.jl, in expression starting on line 68

I managed to bypass it by downloading "glfw-3.1.1.bin.WIN32.zip", and manually and putting it into \.julia\v0.3\GLWF\deps\downloads\. 
I also had to remove:
download("https://github.com/glfw/glfw/releases/download/$version/$build.zip", archive) 
from line 68 from the build.jl file. 

It might have been just a problem on my end, but I thought I would post it here in case it needs fixing.

**Comment by jayschwa** [comment]
Does `download()` work for you in general?

**Comment by UrbanKristan** [comment]
Yeah, now that I checked it doesn't seem to be working for me in general. I got the exact same error when I tried this:
download("https://github.com/JuliaLang/JuliaBox/README.md") (the first file I could find)

Though I'm not sure I'm doing it correctly, as I haven't actually done this before.

**Comment by SimonDanisch** [comment]
For me, this URL is invalid...

**Comment by UrbanKristan** [comment]
Yeah, I was guessing at how to use the download() command, so I just appended the README.md to the end of the URL.

I tried download("https://github.com/kivy/kivy/archive/1.8.0.zip") this time. I'm pretty sure that one's valid, and I still got the same error. So it appears to be on my side. Sorry for wasting your time!

**Comment by jayschwa** [comment]
I'd suggest updating your Julia to v0.3.8 if you haven't already. If you still have `download` problems with the latest version, I suggest you file a ticket on the distribution's repo.
