### ISSUE TITLE
don't use Pkg.dir

### ISSUE THREAD

**Issue by stevengj** [JuliaGL/GLFW.jl#54]
In several places (for example, [here](https://github.com/JuliaGL/GLVisualize.jl/blob/3cee1e7cca0729dfbfaa8b2aad459d2492f3ae0a/src/GLVisualize.jl#L31)), you use `Pkg.dir("GLVisualize", ...)` to find the package directory.  This is wrong, because it breaks for packages that are stored in a system-wide location—see JuliaLang/julia#12120

The right thing to do is one of:

* Use relative paths.  e.g. just `include("types.jl")` rather than `include(joinpath(     sourcedir, "types.jl"))` ... this works, because `include` is always relative to the directory of the current file.

* If an absolute path is needed, use `dirname(@__FILE__)`.

**Comment by SimonDanisch** [comment]
I guess this should go to GLVisualize. Thanks, I didn't realize that this is a problem!

**Comment by stevengj** [comment]
Whoops, sorry for the mislocated issue.
