### ISSUE TITLE
Callbacks are not unique to individual windows

### ISSUE THREAD

**Issue by jayschwa** [JuliaGL/GLFW.jl#63]
Since one global variable is used to store a callback function, it winds up affecting windows that it shouldn't.

**Comment by schlady** [comment]
Can you please merge and tag a new version? :)

**Comment by jayschwa** [comment]
Sorry for letting this languish.

#71 is flawed because callback functions are never garbage-collected. If you're setting callbacks throughout the life of the program, it will leak memory. If you're only setting callbacks once at startup, it's probably fine. That said, I'd prefer to do the next release without such a big known issue. I have a better fix in mind and will implement ASAP now that I know someone is waiting on it :smile:
