### ISSUE TITLE
Deprecation warning trying to use this on v0.5 (readall -> readstring)

### ISSUE THREAD

**Issue by ScottPJones** [JuliaGL/GLFW.jl#77]
I'd like to create a PR to fix this issue, it can be solved either by using `@compat` (however, the requirement of Compat.jl was removed in October), or by specifically handling the name change by checking the Julia version number.

Which would be preferred?

**Comment by jayschwa** [comment]
I don't have a strong preference one way or the other. Since `readstring` doesn't appear to be defined in v0.4, you could possibly just check for its existence and alias it to `readall` if it's not there. That might be a little nicer-looking than a version check.

**Comment by ScottPJones** [comment]
OK, it was much simpler doing it that way, it's just a single line added!
Now builds fine on my Mac with PR #78
