### ISSUE TITLE
GLFW.GetPrimaryMonitor() stackoverflow

### ISSUE THREAD

**Issue by SimonDanisch** [JuliaGL/GLFW.jl#89]
``` Julia
using GLFW
GLFW.GetPrimaryMonitor() 
```

--> StackOverflowError()

**Comment by jayschwa** [comment]
I'm unable to reproduce. There are actually two things happening when you call that. First is the actual call to [`GetPrimaryMonitor`][1]. The second (assuming you're the REPL) is that `show` will be called for the `Monitor` object, which is aliases to [`GetMonitorName`][2].

You should see if you can determine which of these is failing. You might also try calling the same functions from C. That can narrow down if it's a GLFW library bug or something wrong with Julia.

[1]: https://github.com/JuliaGL/GLFW.jl/blob/master/src/glfw3.jl#L311
[2]: https://github.com/JuliaGL/GLFW.jl/blob/master/src/glfw3.jl#L266

**Comment by jayschwa** [comment]
Closing this issue because it's stale and I cannot reproduce. Please reopen if you're still encountering the issue.
