### ISSUE TITLE
GLFW error on Julia 0.5 on Linux with Mesa

### ISSUE THREAD

**Issue by paulmthompson** [JuliaGL/GLFW.jl#96]
I'm getting a seg fault on my Linux machines using GLFW.jl with the current Julia release whenever I try to create a window. I get this error on both of my Linux machines with Mesa (Ubuntu 16.04 and Debian 9). Both of these machines can, however, run GLFW with Julia 0.4, and can use GLFW without Julia. I am having no problems with Julia 0.5 and GLFW on Windows. 

The error message on the Ubuntu 16.04 machine is the following after trying to create a window:

Cannot find target for triple amdgcn-- No available targets are compatible with this triple, see -version for the available targets.

signal (11): Segmentation fault
while loading no file, in expression starting on line 0
LLVMCreateTargetMachine at /home/nicolelislab/julia/usr/bin/../lib/libLLVM-3.7.1.so (unknown line)
unknown function (ip: 0x7fb7fe24fd6e)
unknown function (ip: 0x7fb7fe25005b)
amdgpu_winsys_create at /usr/lib/x86_64-linux-gnu/dri/radeonsi_dri.so (unknown line)
unknown function (ip: 0x7fb7fdcce79e)
unknown function (ip: 0x7fb7fdf5ab93)
unknown function (ip: 0x7fb7fdf570ce)
unknown function (ip: 0x7fb7ffe4e502)
unknown function (ip: 0x7fb7ffe268a3)
glXQueryVersion at /usr/lib/x86_64-linux-gnu/mesa/libGL.so.1 (unknown line)
unknown function (ip: 0x7fb801a39286)
unknown function (ip: 0x7fb801a35171)
glfwCreateWindow at /home/nicolelislab/.julia/v0.5/GLFW/deps/usr/lib/libglfw.so (unknown line)
CreateWindow at /home/nicolelislab/.julia/v0.5/GLFW/src/glfw3.jl:342
#create_glcontext#46 at /home/nicolelislab/.julia/v0.5/GLWindow/src/screen.jl:198
unknown function (ip: 0x7fb805e646d6)
jl_call_method_internal at /home/nicolelislab/julia/src/julia_internal.h:189 [inlined]
jl_apply_generic at /home/nicolelislab/julia/src/gf.c:1945
create_glcontext at /home/nicolelislab/.julia/v0.5/GLWindow/src/screen.jl:181
create_glcontext at /home/nicolelislab/.julia/v0.5/GLWindow/src/screen.jl:181
unknown function (ip: 0x7fb805e62bdf)
jl_call_method_internal at /home/nicolelislab/julia/src/julia_internal.h:189 [inlined]
jl_apply_generic at /home/nicolelislab/julia/src/gf.c:1945
do_call at /home/nicolelislab/julia/src/interpreter.c:66
eval at /home/nicolelislab/julia/src/interpreter.c:190
jl_toplevel_eval_flex at /home/nicolelislab/julia/src/toplevel.c:558 [inlined]
jl_toplevel_eval at /home/nicolelislab/julia/src/toplevel.c:580
jl_toplevel_eval_in_warn at /home/nicolelislab/julia/src/builtins.c:590
eval at ./boot.jl:234
unknown function (ip: 0x7fba2150bf8f)
jl_call_method_internal at /home/nicolelislab/julia/src/julia_internal.h:189 [inlined]
jl_apply_generic at /home/nicolelislab/julia/src/gf.c:1945
eval_user_input at ./REPL.jl:64
unknown function (ip: 0x7fb805e2ea86)
jl_call_method_internal at /home/nicolelislab/julia/src/julia_internal.h:189 [inlined]
jl_apply_generic at /home/nicolelislab/julia/src/gf.c:1945
macro expansion at ./REPL.jl:95 [inlined]
#3 at ./event.jl:68
unknown function (ip: 0x7fb805e2becf)
jl_call_method_internal at /home/nicolelislab/julia/src/julia_internal.h:189 [inlined]
jl_apply_generic at /home/nicolelislab/julia/src/gf.c:1945
jl_apply at /home/nicolelislab/julia/src/julia.h:1392 [inlined]
start_task at /home/nicolelislab/julia/src/task.c:253
unknown function (ip: 0xffffffffffffffff)
Allocations: 8345220 (Pool: 8341152; Big: 4068); GC: 15
Segmentation fault (core dumped)

The Debian 9 error message is similar, but does not include the first line because it uses a slightly different Mesa driver. I can post when I'm at that desk.

I suspect that Mesa and Julia 0.5 are using different LLVM versions, and something is getting confused during one of the calls. Anyone have any other ideas or possible solutions?

Thanks!

**Comment by SimonDanisch** [comment]
Are you sure your Radeon drivers are installed correctly? I think Mesa shouldn't use LLVM if it isn't in software mode.
Can you post the driver version?
Maybe with: `dmesg | grep fglrx`

**Comment by paulmthompson** [comment]
I think the drivers are installed correctly. I'm not having any graphical problems (including GLFW on Julia 0.4) outside of Julia 0.5 on all three of my linux machines. Hopefully I haven't made a habit of messing up the installs on all of them :)

Here is the driver information for one (Debian Stretch):

nicolelislab@dixie:~$ glxinfo | grep -i opengl
ATTENTION: default value of option vblank_mode overridden by environment.
OpenGL vendor string: X.Org
OpenGL renderer string: Gallium 0.4 on AMD TAHITI (DRM 2.43.0, LLVM 3.8.0)
OpenGL core profile version string: 4.1 (Core Profile) Mesa 11.2.2
OpenGL core profile shading language version string: 4.10
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 3.0 Mesa 11.2.2
OpenGL shading language version string: 1.30
OpenGL context flags: (none)
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.0 Mesa 11.2.2
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.00
OpenGL ES profile extensions:

**Comment by paulmthompson** [comment]
Here is another Debian machine:

nicolelislab@shemp:~$ glxinfo | grep -i opengl
OpenGL vendor string: X.Org
OpenGL renderer string: Gallium 0.4 on AMD OLAND
OpenGL core profile version string: 3.3 (Core Profile) Mesa 10.6.8
OpenGL core profile shading language version string: 3.30
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 3.0 Mesa 10.6.8
OpenGL shading language version string: 1.30
OpenGL context flags: (none)
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.0 Mesa 10.6.8
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.00
OpenGL ES profile extensions:

**Comment by paulmthompson** [comment]
Here's one more (ubuntu 16.04):

nicolelislab@curly:~$ glxinfo | grep -i opengl
OpenGL vendor string: X.Org
OpenGL renderer string: Gallium 0.4 on AMD TONGA (DRM 3.1.0, LLVM 3.8.0)
OpenGL core profile version string: 4.1 (Core Profile) Mesa 11.2.0
OpenGL core profile shading language version string: 4.10
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 3.0 Mesa 11.2.0
OpenGL shading language version string: 1.30
OpenGL context flags: (none)
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.0 Mesa 11.2.0
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.00
OpenGL ES profile extensions:

**Comment by SimonDanisch** [comment]
@kfischer suggested that this is a bug in the Linux distribution, which does indeed end up in dynamically linking the wrong LLVM lib.
For a fix, try linkinkg LLVM statically. So when building Julia, insert this line `override USE_LLVM_SHLIB = 0` into `Make.user` (or create it if not already present).
Hope that helps! :)

**Comment by paulmthompson** [comment]
Bullseye. That worked! Thanks!

So does this mean that Julia dynamically links LLVM by default? If so, should we change this line in the documentation:

"Julia statically links in LLVM by default. Build with USE_LLVM_SHLIB=1 to link dynamically."
http://docs.julialang.org/en/release-0.5/devdocs/llvm/
