### ISSUE TITLE
folder not found when building

### ISSUE THREAD

**Issue by SimonDanisch** [JuliaGL/GLFW.jl#98]
On OSX, GLFW doesn't build successfully after homebrew fails.
Is this an issue with Bindeps? For linux it seems to work fine.

```Julia
LoadError: could not spawn `cmake -DBUILD_SHARED_LIBS=ON -DCMAKE_INSTALL_PREFIX=/Applications/JuliaPro-0.5.0.2.app/Contents/Resources/pkgs-0.5.0.2/v0.5/GLFW/deps/usr -DGLFW_BUILD_DOCS=OFF -DGLFW_BUILD_EXAMPLES=OFF -DGLFW_BUILD_TESTS=OFF .`: no such file or directory (ENOENT)
while loading /Applications/JuliaPro-0.5.0.2.app/Contents/Resources/pkgs-0.5.0.2/v0.5/GLFW/deps/build.jl, in expression starting on line 52
```
Or is the error message confusing and it's just that cmake is missing?

Best,
Simon

**Comment by jayschwa** [comment]
It's probably `cmake` missing. But why is Homebrew trying to build it rather than using a precompiled binary?

**Comment by SimonDanisch** [comment]
That'd be the next question ;) I opened an issue about this: 
https://github.com/JuliaPackaging/Homebrew.jl/issues/172#issuecomment-270740561
The road to a completely hassle free GLVisualize installation doesn't come easy, it seems :P

**Comment by biogeo** [comment]
I just ran into this, as well -- installing cmake fixed it.  Also I had to install the following packages in order to get GLFW.jl to build (Ubuntu 16.10):

    cmake
    libxrandr-dev
    libxinerama-dev
    libxcursor-dev

Might be handy to include these in installation instructions for Ubuntu:

    sudo apt-get install cmake libxrandr-dev libxinerama-dev libxcursor-dev

**Comment by ssfrr** [comment]
Ran into this also (on Linux). If you want to supply platform binaries I've had pretty good luck setting up a mini "build farm" using docker, so users don't need to have a build environment on their system:

https://github.com/JuliaAudio/RingBuffers.jl/tree/master/deps/src

`build.sh` is the top-level script that spawns the various docker boxes and runs the makefile in each one. I just run it locally to generate all the library builds that I distribute in `deps/usr/lib`

**Comment by SimonDanisch** [comment]
That sounds a lot like how Bindeps2 is supposed to work... Maybe we can just switch over when it's released :)

**Comment by SimonEnsemble** [comment]
I ran into this error as well. `sudo apt-get install cmake libxrandr-dev libxinerama-dev libxcursor-dev` solved it on Ubuntu 16.04

**Comment by SimonDanisch** [comment]
I added a note to the README: https://github.com/JuliaGL/GLFW.jl/pull/115

**Comment by musm** [comment]
probably can close since this is now using Binary Builder
