### ISSUE TITLE
Fix for FreeBSD

### ISSUE THREAD

**Issue by ko56** [JuliaGL/GLFW.jl#99]
In ModernGL/src/ModernGL.jl, line 29: change is_linux() to is_unix(). Then Pkg.test("GLFW") passes.

**Comment by jayschwa** [comment]
@SimonDanisch

**Comment by SimonDanisch** [comment]
Oh yeah sorry! I meant to add a PR for this, but didn't get to it. Partly, because I won't be able to test the change. @ko56, might you be willing to submit a pr doing just this?
Note, that `is_unix()` == `is_apple()`, when on Apple ;)

**Comment by ko56** [comment]
I'm not sure how to submit a pr :-)
But anyhow, do you suggest changing is_unix to is_freebsd?

**Comment by SimonDanisch** [comment]
that function doesn't exist.. Ah well, let me just make that PR and let you test it ;)

**Comment by SimonDanisch** [comment]
https://github.com/JuliaGL/ModernGL.jl/pull/33

**Comment by ko56** [comment]
I meant is_bsd().

**Comment by ko56** [comment]
Ok, it works.

**Comment by SimonDanisch** [comment]
Great :)
